// Fonte única de dados da ecooa.
// A ordem deste array é a ordem de exibição na página de profissionais.
// registro.estado: 'confirmado' | 'a-confirmar' | 'a-adicionar'
(function () {
  const P = 'assets/retratos/';

  const profissionais = [
    // ─────────── médicos ───────────
    { slug:'gustavo-gehrke', nome:'Gustavo Gehrke', primeiro:'Gustavo', foto:P+'gustavo-gehrke pb.webp',
      classe:'Médico', grupo:'medicina', marca:'ecooa.med · ecooa.esthetic', papel:'sócio fundador',
      registro:'CRM-RS 35.822', estado:'confirmado', area:'metabolismo, emagrecimento e hormônios',
      esp:['medicina'],
      bio:'Sócio da ecooa, empreendedor e médico de abordagem clínica ampla. Atua com medicina metabólica, emagrecimento, saúde hormonal, performance, longevidade e acompanhamento de doenças crônicas.',
      conduta:'Com formação complementar em Medicina de Família e Comunidade, Medicina do Exercício e do Esporte, práticas ortomoleculares e metabolômica, Gustavo conduz uma avaliação ampla da saúde, integrando sintomas, histórico clínico, estilo de vida, composição corporal e interpretação detalhada de exames laboratoriais.\n\nSua abordagem busca compreender os mecanismos envolvidos em alterações metabólicas, dificuldade para emagrecer, desequilíbrios hormonais, redução de performance e doenças crônicas, antes de definir qualquer conduta.\n\nNa consulta, organiza informações complexas, diferencia evidências consistentes de modismos e revê conceitos que se tornaram simplificados ou ultrapassados. Evita tanto promessas fáceis quanto proibições generalizadas, construindo estratégias individualizadas, compreensíveis e possíveis de manter ao longo do tempo.',
      atendimento:'presencial e online' },
    { slug:'larissa-wiebbelling', nome:'Larissa Wiebbelling', primeiro:'Larissa', foto:P+'larissa pb.webp',
      classe:'Médica', grupo:'medicina', marca:'ecooa.med · ecooa.esthetic', papel:'',
      registro:'CRM-RS 55.504', estado:'confirmado', area:'transplante capilar e tricologia médica',
      esp:['medicina','tricologia','transplante-capilar'],
      bio:'Transplante capilar, transplante de barba, transplante de sobrancelha e tricologia. Atua com avaliação capilar, técnica sem raspagem, técnica com fio longo e acompanhamento completo do pré ao pós-procedimento.',
      conduta:'Antes de indicar qualquer transplante capilar, Larissa avalia a área doadora, a área receptora, o padrão de queda, a qualidade dos fios e a viabilidade do procedimento para cada caso.\n\nSua atuação envolve transplante capilar masculino e feminino, transplante de barba, transplante de sobrancelha, técnica sem raspagem e técnica com fio longo, indicada para pacientes que desejam preservar melhor a aparência dos cabelos durante o processo.\n\nCom experiência em transplantes capilares, conduz o paciente desde a primeira avaliação até o pós-procedimento, alinhando expectativa, planejamento técnico, cuidado tricologista e acompanhamento da evolução para buscar um resultado natural, seguro e compatível com cada indicação.',
      atendimento:'presencial' },
    { slug:'yale-jeronimo', nome:'Yale Jerônimo', primeiro:'Yale', foto:P+'yale pb.webp',
      classe:'Médica', grupo:'medicina', marca:'ecooa.med · ecooa.esthetic', papel:'',
      registro:'CRM-RS 49.185', estado:'confirmado', area:'tricologia e alopecias',
      esp:['medicina','tricologia'],
      bio:'Médica tricologista, empreendedora e especialista no diagnóstico e tratamento médico das alopecias. Atua com queda de cabelo, doenças do couro cabeludo, saúde dos fios e estética capilar.',
      conduta:'Com olhar médico para as doenças do cabelo e do couro cabeludo, Yale conduz pacientes que enfrentam queda capilar, afinamento dos fios, alopecias, alterações inflamatórias e perda de densidade.\n\nSua abordagem integra avaliação clínica, investigação diagnóstica, análise do couro cabeludo e definição de estratégias individualizadas para tratar a causa do problema e melhorar a qualidade dos fios desde a raiz.\n\nAtendendo em Porto Alegre e também em sua clínica em Gramado, Yale oferece uma experiência de cuidado capilar que une medicina, tricologia e estética, com orientação clara, acompanhamento próximo e foco em saúde, aprendizado e evolução durante o tratamento.',
      atendimento:'presencial' },
    { slug:'vitoria-machado', nome:'Vitória Müller T. Machado', primeiro:'Vitória', foto:P+'vitoria-machado pb.webp',
      classe:'Médica dermatologista', grupo:'medicina', marca:'ecooa.med · ecooa.esthetic', papel:'',
      registro:'CRM-RS 43.712 · RQE 42.218', estado:'confirmado', area:'dermatologia clínica e estética',
      esp:['medicina','estetica-facial'],
      bio:'Dermatologia clínica e estética.',
      conduta:'Avalia a pele como um todo antes de tratar uma queixa isolada, e prioriza a rotina de cuidado que sustenta o resultado ao longo do tempo.',
      atendimento:'presencial' },
    { slug:'renata-bohn-engel', nome:'Renata Bohn Engel', primeiro:'Renata', foto:P+'renata pb.webp',
      classe:'Médica dermatologista', grupo:'medicina', marca:'ecooa.med · ecooa.esthetic', papel:'',
      registro:'CRM-RS 48.838 · RQE 46.857', estado:'confirmado', area:'dermatologia clínica e estética',
      esp:['medicina','estetica-facial'],
      bio:'Dermatologia clínica e estética, do diagnóstico ao cuidado contínuo com a pele.',
      conduta:'Trata a pele como um órgão com história. Diagnóstico primeiro, rotina depois, e procedimento apenas quando ele acrescenta ao que o cuidado diário já sustenta.',
      atendimento:'presencial' },

    // ─────────── nutricionistas ───────────
    { slug:'jessica-stein', nome:'Jessica Stein', primeiro:'Jessica', foto:P+'jessica .webp',
      classe:'Nutricionista', grupo:'nutricao', marca:'ecooa.working · ecooa.cademy', papel:'sócia e diretora de ensino',
      registro:'CRN 9495', estado:'confirmado', area:'nutrição clínica, vegetariana e emagrecimento',
      esp:['nutricao'],
      bio:'Sócia da ecooa, empreendedora e professora de pós-graduação. Atua com nutrição clínica, alimentação vegetariana e vegana, nutrição materno-infantil, acompanhamento de gestantes e crianças, emagrecimento e mentorias individuais para nutricionistas.',
      conduta:'Com experiência na interpretação de exames bioquímicos, mais de dez anos de prática do veganismo e atuação no ensino de pós-graduação, Jessica conduz consultas personalizadas para vegetarianos, veganos e não vegetarianos.\n\nSua abordagem integra avaliação clínica, rotina alimentar, estilo de vida e objetivos individuais para acompanhar gestantes, crianças, pessoas em processo de emagrecimento e pacientes que utilizam medicamentos para controle do peso, incluindo as chamadas canetas emagrecedoras.\n\nNa ecooa, em Porto Alegre, e no atendimento online, combina atualização científica, didática e acompanhamento próximo, explicando o motivo de cada escolha e ajustando a estratégia nutricional ao longo do processo.',
      atendimento:'presencial e online' },
    { slug:'adriano-lenz', nome:'Adriano Flesch Lenz', primeiro:'Adriano', foto:P+'Adriano pb.webp',
      classe:'Nutricionista', grupo:'nutricao', marca:'ecooa.working', papel:'',
      registro:'CRN-2 7844D', estado:'confirmado', area:'nutrição e práticas ortomoleculares',
      esp:['nutricao','saude-integrativa'],
      bio:'Nutricionista, mestre em Bioquímica e acadêmico de Medicina. Atua com nutrição clínica, hipertrofia, emagrecimento, composição corporal e práticas ortomoleculares.',
      conduta:'Com mais de 15 anos de carreira na nutrição, mestrado em Bioquímica e pós-graduação em práticas ortomoleculares, Adriano une experiência clínica, base científica e estudo contínuo para construir estratégias nutricionais individualizadas.\n\nSua atuação é voltada para pacientes que buscam emagrecimento, ganho de massa muscular, melhora da composição corporal, performance, organização alimentar e acompanhamento metabólico com maior precisão.\n\nComo acadêmico de Medicina, amplia sua visão sobre saúde, exames, fisiologia e tomada de decisão clínica, integrando nutrição, bioquímica aplicada e prática assistencial. Atende em Porto Alegre, em Santa Maria e online, mantendo o mesmo padrão de avaliação, planejamento e acompanhamento em cada formato.',
      atendimento:'presencial e online' },
    { slug:'giancarla-rochemback', nome:'Giancarla Rochemback', primeiro:'Giancarla', foto:P+'giancarla fp.webp',
      classe:'Nutricionista', grupo:'nutricao', marca:'ecooa.working', papel:'',
      registro:'', estado:'a-adicionar', area:'nutrição clínica e esportiva',
      esp:['nutricao'],
      bio:'Nutrição clínica e esportiva.',
      conduta:'Alinha a estratégia nutricional ao volume real de treino e à rotina de trabalho.',
      atendimento:'presencial e online' },
    { slug:'maria-luisa-borges', nome:'Maria Luísa Serrano Beltran Borges', primeiro:'Maria Luísa', foto:P+'maria-luisa pb.webp',
      classe:'Nutricionista', grupo:'nutricao', marca:'ecooa.working', papel:'',
      registro:'CRN-2 12076P', estado:'a-confirmar', area:'nutrição esportiva e alta performance',
      esp:['nutricao'],
      bio:'Nutrição esportiva e alta performance esportiva.',
      conduta:'Trabalha a alimentação como parte do treino, com ajuste conforme a fase da temporada e o objetivo de competição.',
      atendimento:'presencial e online' },
    { slug:'daniel-forster', nome:'Daniel Forster', primeiro:'Daniel', foto:P+'daniel pb.webp',
      classe:'Nutricionista', grupo:'nutricao', marca:'ecooa.working', papel:'',
      registro:'CRN2 20541', estado:'confirmado', area:'nutrição clínica e esportiva',
      esp:['nutricao'],
      bio:'Nutrição clínica e esportiva, emagrecimento.',
      conduta:'Trabalha com metas mensuráveis e revisão periódica, sem dieta genérica e sem promessa de prazo.',
      atendimento:'presencial e online' },
    { slug:'vitoria-serpa', nome:'Vitória Serpa da Silva', primeiro:'Vitória', foto:P+'vitoria-serpa pb.webp',
      classe:'Nutricionista', grupo:'nutricao', marca:'ecooa.working', papel:'',
      registro:'CRN-2 12000P', estado:'a-confirmar', area:'nutrição esportiva',
      esp:['nutricao'],
      bio:'Nutrição esportiva.',
      conduta:'Considera rotina de treino, sono e histórico alimentar antes de propor qualquer estratégia.',
      atendimento:'presencial e online' },
    { slug:'nasser-salem', nome:'Nasser Salem', primeiro:'Nasser', foto:P+'nasser pb.webp',
      classe:'Nutricionista', grupo:'nutricao', marca:'ecooa.working', papel:'',
      registro:'CRN2 19914D', estado:'confirmado', area:'nutrição esportiva e emagrecimento',
      esp:['nutricao'],
      bio:'Nutrição esportiva, emagrecimento e performance sem modismo.',
      conduta:'Começa por hábitos, não por suplementos, e mede o resultado antes de acrescentar qualquer coisa.',
      atendimento:'presencial e online' },
    { slug:'marvin-marques', nome:'Marvin Marques', primeiro:'Marvin', foto:P+'marvin.webp',
      classe:'Nutricionista', grupo:'nutricao', marca:'ecooa.working', papel:'',
      registro:'', estado:'a-adicionar', area:'nutrição clínica e emagrecimento',
      esp:['nutricao'],
      bio:'Nutrição clínica e emagrecimento.',
      conduta:'Investiga rotina, sono e histórico alimentar antes de propor mudança, e ajusta conforme a resposta.',
      atendimento:'presencial e online' },
    { slug:'gabrieli-avila', nome:'Gabrieli Klagenberg Avila', primeiro:'Gabrieli', foto:P+'gabrielli fp.webp',
      classe:'Nutricionista', grupo:'nutricao', marca:'ecooa.working', papel:'',
      registro:'', estado:'a-adicionar', area:'nutrição comportamental',
      esp:['nutricao'],
      bio:'Nutrição comportamental.',
      conduta:'Trabalha a relação com a comida antes do cardápio, porque é ela que decide o que se sustenta depois.',
      atendimento:'presencial e online' },
    { slug:'camila-cadore', nome:'Camila Cadore', primeiro:'Camila', foto:P+'camila fp.webp',
      classe:'Nutricionista', grupo:'nutricao', marca:'ecooa.working', papel:'',
      registro:'CRN/RS 8447', estado:'a-confirmar', area:'nutrição funcional e integrativa',
      esp:['nutricao','saude-integrativa'],
      bio:'Nutrição funcional e integrativa, saúde, família e conexão entre mente e corpo.',
      conduta:'Olha para a alimentação dentro do contexto de vida inteiro, incluindo sono, rotina e vínculos.',
      atendimento:'presencial e online' },
    { slug:'verena-cattani', nome:'Verena Cattani', primeiro:'Verena', foto:P+'verena pb.webp',
      classe:'Nutricionista', grupo:'nutricao', marca:'ecooa.working', papel:'',
      registro:'CRN 2 19692', estado:'confirmado', area:'nutrição clínica',
      esp:['nutricao'],
      bio:'Nutrição clínica, saúde intestinal e cuidado nutricional na endometriose.',
      conduta:'Trabalha com sintomas que costumam ser normalizados, e organiza a investigação junto com a equipe médica quando é o caso.',
      atendimento:'presencial e online' },
    { slug:'lara-caye', nome:'Lara Caye', primeiro:'Lara', foto:P+'lara-caye pb.webp',
      classe:'Nutricionista', grupo:'nutricao', marca:'ecooa.working', papel:'',
      registro:'', estado:'a-adicionar', area:'nutrição esportiva e hipertrofia',
      esp:['nutricao'],
      bio:'Nutrição esportiva, hipertrofia e consultoria online.',
      conduta:'Acompanha treino, composição corporal e alimentação como um sistema único, com ajustes frequentes.',
      atendimento:'presencial e online' },

    // ─────────── estética, tricologia e integrativa ───────────
    { slug:'danusa-pires', nome:'Danusa Pires', primeiro:'Danusa', foto:P+'danusa fp.webp',
      classe:'Enfermeira', grupo:'estetica', marca:'ecooa.esthetic · ecooa.health', papel:'',
      registro:'COREN-RS 395164', estado:'confirmado', area:'tricologia estética e reposição de nutrientes',
      esp:['tricologia','saude-integrativa'],
      bio:'Tricologia estética, saúde do couro cabeludo e terapias de reposição de nutrientes. Atua no cuidado da queda capilar feminina, fortalecimento dos fios e melhora da densidade capilar.',
      conduta:'Idealizadora do Método Ascensão Capilar, Danusa conduz mulheres que desejam recuperar a saúde, a força e a qualidade dos cabelos por meio de uma jornada estruturada de cuidado capilar.\n\nEm vez de oferecer procedimentos isolados, sua abordagem integra avaliação do couro cabeludo, identificação de fatores associados à queda, acompanhamento da evolução e combinação personalizada de estratégias de tricologia estética, fortalecimento dos fios e reposição de nutrientes.\n\nO objetivo é desenvolver, com continuidade e acompanhamento próximo, o melhor potencial de densidade, resistência e qualidade capilar compatível com as necessidades de cada organismo.',
      atendimento:'presencial' },
    { slug:'viviane-fagundes', nome:'Viviane Fagundes', primeiro:'Viviane', foto:P+'viviane pb.webp',
      classe:'Biomédica', grupo:'estetica', marca:'ecooa.esthetic', papel:'',
      registro:'CRBM 2565', estado:'confirmado', area:'tricologia estética e testes genéticos capilares',
      esp:['tricologia'],
      bio:'Tricologia estética e testes genéticos aplicados à saúde capilar. Atua na avaliação da queda de cabelo, no fortalecimento dos fios e no acompanhamento personalizado de tratamentos capilares.',
      conduta:'Viviane utiliza a avaliação do couro cabeludo e, quando indicado, testes genéticos capilares para identificar características individuais que possam ajudar a direcionar o cuidado com maior precisão. Proprietária da TriviHair, em Gravataí, também atende presencialmente em Porto Alegre.\n\nSua abordagem é especialmente útil para pessoas que convivem há mais tempo com queda de cabelo, redução de densidade ou resposta limitada a tratamentos anteriores. Os achados genéticos são interpretados em conjunto com o histórico, os sinais clínicos e a evolução de cada paciente, sem substituir a avaliação médica.\n\nEm integração com o médico responsável, acompanha pacientes que utilizam minoxidil e outros medicamentos para queda capilar, combinando o tratamento clínico com estratégias de tricologia estética e monitoramento contínuo dos resultados.',
      atendimento:'presencial' },
    { slug:'natalie-queiroz', nome:'Natálie Queiroz', primeiro:'Natálie', foto:P+'natalie pb.webp',
      classe:'Osteopata e fisioterapeuta', grupo:'fisioterapia', marca:'ecooa.health', papel:'',
      registro:'CREFITO-5 271577-F', estado:'confirmado', area:'osteopatia adulto e infantil',
      esp:['saude-integrativa'],
      bio:'Osteopatia para adultos e crianças. Atua no cuidado de dores crônicas, lesões musculoesqueléticas, alterações de movimento, postura funcional e acompanhamento osteopático de bebês.',
      conduta:'Natálie conduz o cuidado com foco em movimento, função e consciência corporal, indo além do alívio imediato da dor que trouxe o paciente à consulta.\n\nPor meio de avaliação física, escuta clínica, técnicas osteopáticas e orientação de exercícios, busca compreender como postura, mobilidade, respiração, rotina e padrões de movimento podem estar contribuindo para dores crônicas, lesões recentes ou limitações funcionais.\n\nTambém atua no cuidado osteopático infantil, acompanhando bebês em situações relacionadas a conforto corporal, assimetrias, tensões, adaptação pós-parto e dificuldades que podem interferir na amamentação. Sua abordagem é individualizada, segura e orientada para evolução funcional ao longo do tratamento.',
      atendimento:'presencial' },
    { slug:'susan-flach', nome:'Susan Flach', primeiro:'Susan', foto:P+'susan pb.webp',
      classe:'Biomédica', grupo:'estetica', marca:'ecooa.esthetic', papel:'',
      registro:'CRBM-5 4182', estado:'confirmado', area:'tricologia e gerenciamento da pele',
      esp:['tricologia','estetica-facial'],
      bio:'Tricologia e gerenciamento da pele.',
      conduta:'Constrói rotina domiciliar antes de indicar procedimento, porque é ela que sustenta o resultado.',
      atendimento:'presencial' },
    { slug:'leticia-melo', nome:'Letícia Melo', primeiro:'Letícia', foto:P+'leticia.webp',
      classe:'Biomédica', grupo:'estetica', marca:'ecooa.esthetic', papel:'',
      registro:'CRBM-RS 627', estado:'confirmado', area:'harmonização orofacial',
      esp:['estetica-facial'],
      bio:'Harmonização orofacial.',
      conduta:'Lê o rosto inteiro antes de tratar uma região, e trabalha para preservar a expressão.',
      atendimento:'presencial' },
    { slug:'eduarda-schoenmeier', nome:'Eduarda Schoenmeier', primeiro:'Eduarda', foto:P+'eduarda pb.webp',
      classe:'Biomédica esteta', grupo:'estetica', marca:'ecooa.esthetic', papel:'',
      registro:'CRBM 7243', estado:'confirmado', area:'harmonização orofacial e corporal',
      esp:['estetica-facial','estetica-corporal'],
      bio:'Harmonização orofacial e corporal.',
      conduta:'Planeja em etapas, com expectativa combinada antes de começar e reavaliação a cada retorno.',
      atendimento:'presencial' },
    { slug:'tais-de-la-rosa', nome:'Tais de la Rosa', primeiro:'Tais', foto:P+'Tais pb.webp',
      classe:'Farmacêutica', grupo:'estetica', marca:'ecooa.esthetic', papel:'',
      registro:'CRF-RS 588527', estado:'a-confirmar', area:'harmonização orofacial e saúde da pele',
      esp:['estetica-facial'],
      bio:'Harmonização orofacial e saúde da pele com embasamento científico.',
      conduta:'Monta rotina de cuidado com ativos justificados, e descarta o que não tem evidência para aquele caso.',
      atendimento:'presencial' },
    { slug:'karine-ellwanger', nome:'Karine Ellwanger', primeiro:'Karine', foto:P+'karine fp.webp',
      classe:'Biomédica esteta', grupo:'estetica', marca:'ecooa.esthetic', papel:'',
      registro:'CRBM-5 7474', estado:'confirmado', area:'harmonização orofacial',
      esp:['estetica-facial'],
      bio:'Harmonização orofacial.',
      conduta:'Explica o que cada técnica faz e o que ela não faz, antes de qualquer decisão.',
      atendimento:'presencial' },
    { slug:'jennifer-adam', nome:'Jennifer Adam', primeiro:'Jennifer', foto:P+'jennifer fp.webp',
      classe:'Biomédica esteta', grupo:'estetica', marca:'ecooa.esthetic', papel:'',
      registro:'CRBM-5 8600', estado:'confirmado', area:'harmonização orofacial e rejuvenescimento',
      esp:['estetica-facial'],
      bio:'Harmonização orofacial e rejuvenescimento.',
      conduta:'Prefere resultado discreto e progressivo ao efeito imediato que se percebe de longe.',
      atendimento:'presencial' },
    { slug:'jamylle-farias', nome:'Jamylle Farias', primeiro:'Jamylle', foto:P+'jamylle pb.webp',
      classe:'Cirurgiã-dentista', grupo:'estetica', marca:'ecooa.esthetic', papel:'',
      registro:'CRO-RS 30124', estado:'confirmado', area:'harmonização orofacial',
      esp:['estetica-facial'],
      bio:'Harmonização orofacial.',
      conduta:'Avalia proporção e função antes de estética, e recusa o procedimento quando ele não acrescenta ao rosto da pessoa.',
      atendimento:'presencial' },
    { slug:'adriana', nome:'Adriana', primeiro:'Adriana', foto:P+'adriana pb.webp',
      classe:'Terapeuta integrativa', grupo:'terapia-integrativa', marca:'ecooa.health', papel:'',
      registro:'', estado:'a-adicionar', area:'terapia integrativa e biorressonância',
      esp:['saude-integrativa'],
      bio:'Terapia integrativa e biorressonância.',
      conduta:'Trabalha como cuidado complementar, sempre em diálogo com o acompanhamento clínico de cada pessoa.',
      atendimento:'presencial' },

    // ─────────── psicólogos ───────────
    { slug:'manuela-vanti', nome:'Manuela Sinigaglia Vanti', primeiro:'Manuela', foto:P+'manuela pb.webp',
      classe:'Psicóloga', grupo:'saude-mental', marca:'ecooa.mind', papel:'',
      registro:'CRP 07/34596', estado:'confirmado', area:'terapia cognitivo-comportamental',
      esp:['saude-mental'],
      bio:'Terapia cognitivo-comportamental, presencial e online.',
      conduta:'Constrói o processo no ritmo de quem chega, com espaço para o que ainda não tem nome.',
      atendimento:'presencial e online' },
    { slug:'augusto-kauer', nome:'Augusto Kauer da Silveira', primeiro:'Augusto', foto:P+'augusto pb.webp',
      classe:'Psicólogo', grupo:'saude-mental', marca:'ecooa.mind', papel:'',
      registro:'CRP 07/28516', estado:'a-confirmar', area:'psicologia do esporte',
      esp:['saude-mental'],
      bio:'Psicologia do esporte, para quem treina, compete ou vive sob pressão de resultado.',
      conduta:'Escuta antes de propor técnica. O trabalho parte do que a pessoa quer sustentar, não de um protocolo pronto.',
      atendimento:'presencial e online' },
    { slug:'francielle-beria', nome:'Francielle Machado Beria', primeiro:'Francielle', foto:P+'francielly fp.webp',
      classe:'Psicóloga', grupo:'saude-mental', marca:'ecooa.mind', papel:'',
      registro:'CRP 07/29944', estado:'confirmado', area:'terapia cognitivo-comportamental e neuropsicologia',
      esp:['saude-mental'],
      bio:'Terapia cognitivo-comportamental e neuropsicologia, presencial e online.',
      conduta:'Trabalha com objetivos combinados e revisados, e explica o raciocínio por trás de cada etapa do processo.',
      atendimento:'presencial e online' },
  ];

  const grupos = [
    { slug:'medicina', nome:'medicina' },
    { slug:'nutricao', nome:'nutrição' },
    { slug:'estetica', nome:'estética' },
    { slug:'fisioterapia', nome:'fisioterapia' },
    { slug:'saude-mental', nome:'saúde mental' },
    { slug:'terapia-integrativa', nome:'terapia integrativa' },
  ];

  const especialidades = [
    { slug:'medicina', nome:'Medicina', marca:'ecooa.med', foto:'assets/fotos/med.webp',
      resumo:'Medicina metabólica, hormônios, longevidade e performance, com tempo de consulta e leitura de exames explicada.',
      escopo:['Medicina metabólica e endocrinológica','Nutrologia e emagrecimento','Envelhecimento saudável','Performance cognitiva e física','Hormônios em saúde feminina e masculina','Medicina do esporte','Medicina preventiva e checkup metabólico','Dermatologia clínica'],
      como:['Primeira consulta longa, com história completa e o que já foi tentado.','Exames pedidos com propósito, e devolvidos com explicação.','Plano escrito, com o que fazer e o que observar.','Retorno programado para revisar e ajustar.'],
      faq:[
        { q:'Quanto tempo dura a primeira consulta?', a:'A primeira consulta é longa por escolha, porque a história clínica é o principal instrumento de trabalho. O tempo exato é combinado no agendamento.' },
        { q:'Vocês trabalham com emagrecimento medicamentoso?', a:'A conduta é individual e depende de avaliação clínica. Quando há indicação, a classe farmacológica e os riscos são explicados antes de qualquer decisão. Não indicamos medicação por demanda.' },
        { q:'Preciso levar exames anteriores?', a:'Sim, todos que tiver, mesmo antigos. A comparação ao longo do tempo costuma dizer mais do que um exame isolado.' },
      ] },
    { slug:'estetica-facial', nome:'Estética facial', marca:'ecooa.esthetic', foto:'assets/fotos/esthetic.webp',
      resumo:'Dermatologia, harmonização orofacial e refinamento, com indicação honesta e resultado que preserva a expressão.',
      escopo:['Dermatologia clínica e estética','Harmonização orofacial','Rejuvenescimento facial','Refinamento e proporção','Cuidado e rotina de pele','Acne e manchas'],
      como:['Avaliação do rosto inteiro, não da queixa isolada.','Expectativa combinada por escrito antes de começar.','Procedimento apenas quando acrescenta ao cuidado diário.','Reavaliação a cada retorno.'],
      faq:[
        { q:'Vocês mostram fotos de antes e depois?', a:'Não. É uma decisão ética da ecooa e alinhada às normas de publicidade em saúde. Na consulta, o profissional explica o que é possível para o seu caso.' },
        { q:'Quanto tempo dura o resultado?', a:'Depende da técnica, da região e de cada organismo. O profissional informa a faixa esperada na avaliação, sem prometer duração fixa.' },
        { q:'Posso combinar procedimento com tratamento dermatológico?', a:'Sim, e é comum. Quando isso acontece, os profissionais envolvidos conversam entre si sobre a sequência adequada.' },
      ] },
    { slug:'estetica-corporal', nome:'Estética corporal', marca:'ecooa.esthetic', foto:'assets/fotos/esthetic.webp',
      resumo:'Contorno, firmeza e cuidado corporal, planejados em etapas e integrados ao acompanhamento nutricional e clínico.',
      escopo:['Harmonização corporal','Firmeza e contorno','Cuidado pós-procedimento','Integração com nutrição e fisioterapia'],
      como:['Avaliação do objetivo e do contexto de saúde.','Plano em etapas, com intervalos respeitados.','Encaminhamento interno quando o resultado depende de nutrição ou movimento.','Reavaliação antes de qualquer nova sessão.'],
      faq:[
        { q:'Estética corporal substitui acompanhamento nutricional?', a:'Não. Quando o objetivo envolve composição corporal, o cuidado é conduzido junto com nutrição e, quando indicado, com movimento.' },
        { q:'Em quantas sessões vejo resultado?', a:'Varia por técnica e por pessoa. O profissional apresenta a faixa esperada na avaliação e reavalia a cada etapa.' },
      ] },
    { slug:'tricologia', nome:'Tricologia', marca:'ecooa.esthetic', foto:'assets/fotos/esthetic.webp',
      resumo:'Investigação e tratamento da queda de cabelo e das doenças do couro cabeludo, com equipe médica, biomédica e de enfermagem.',
      escopo:['Investigação da queda capilar','Alopecias','Doenças do couro cabeludo','Testes genéticos capilares','Protocolos de tratamento capilar','Acompanhamento de longo prazo'],
      como:['Investigação clínica da causa antes de qualquer protocolo.','Exames quando necessários para diferenciar as causas.','Protocolo com registro da evolução sessão a sessão.','Reavaliação nos meses em que o cabelo leva para responder.'],
      faq:[
        { q:'Queda de cabelo sempre tem tratamento?', a:'Nem toda queda tem a mesma causa, e nem toda causa tem o mesmo caminho. A investigação existe justamente para responder isso com honestidade no seu caso.' },
        { q:'Em quanto tempo eu vejo diferença?', a:'O ciclo capilar é lento. A reavaliação costuma acontecer em meses, não em semanas, e isso é combinado desde a primeira consulta.' },
      ] },
    { slug:'transplante-capilar', nome:'Transplante capilar', marca:'ecooa.esthetic', foto:'assets/fotos/esthetic.webp',
      resumo:'Cirurgia capilar conduzida por médica, com investigação prévia e critério claro sobre quem tem e quem não tem indicação.',
      escopo:['Avaliação de indicação cirúrgica','Planejamento de linha e densidade','Procedimento cirúrgico','Acompanhamento pós-operatório','Tratamento clínico associado'],
      como:['Consulta de avaliação com investigação da causa da queda.','Indicação apenas quando há critério clínico para isso.','Planejamento discutido antes do agendamento da cirurgia.','Pós-operatório acompanhado, com tratamento clínico associado.'],
      faq:[
        { q:'Todo mundo pode fazer transplante capilar?', a:'Não. Existem critérios clínicos, e há casos em que o tratamento adequado é outro. Quando não há indicação, a médica diz e aponta o caminho correto.' },
        { q:'O procedimento resolve a causa da queda?', a:'O transplante recompõe densidade em áreas específicas. A causa da queda continua precisando de acompanhamento clínico, e por isso os dois caminham juntos.' },
      ] },
    { slug:'nutricao', nome:'Nutrição', marca:'ecooa.working', foto:'assets/fotos-tratadas/working-perola-fria.webp',
      resumo:'Nutrição clínica, esportiva, comportamental, vegetariana e funcional. Doze profissionais, cada um com um foco, para que a conduta caiba na sua rotina.',
      escopo:['Nutrição clínica','Nutrição esportiva e alta performance','Emagrecimento','Nutrição comportamental','Nutrição vegetariana','Hipertrofia e composição corporal','Nutrição funcional e integrativa','Práticas ortomoleculares'],
      como:['Anamnese alimentar e de rotina, antes do plano.','Metas combinadas e mensuráveis.','Ajuste periódico conforme a resposta.','Conversa com a equipe médica quando o caso pede.'],
      faq:[
        { q:'Vocês passam dieta pronta?', a:'Não. O plano é construído a partir da sua rotina, dos seus horários e do que você consegue manter. Plano que não cabe na vida real não funciona.' },
        { q:'Em quanto tempo eu emagreço?', a:'Não trabalhamos com prazo prometido. O acompanhamento define metas realistas e revisa a cada retorno, com atenção à saúde e não apenas ao número.' },
      ] },
    { slug:'saude-mental', nome:'Saúde mental', marca:'ecooa.mind', foto:'assets/fotos-tratadas/mind-perola-fria.webp',
      resumo:'Psicologia clínica, do esporte e neuropsicologia. Escuta sem pressa, presencial e online.',
      escopo:['Psicologia clínica','Terapia cognitivo-comportamental','Neuropsicologia','Psicologia do esporte','Atendimento online'],
      como:['Primeira conversa para entender demanda e expectativa.','Combinação de objetivos e de frequência.','Processo revisado periodicamente.','Articulação com a equipe quando faz sentido para o cuidado.'],
      faq:[
        { q:'Quanto tempo dura um processo terapêutico?', a:'Depende da demanda e do que se busca. Isso é conversado logo no início e revisto ao longo do processo, sem pacote fechado.' },
        { q:'O atendimento online funciona igual?', a:'Para muitas demandas, sim. A escolha entre presencial e online é feita junto com a psicóloga na primeira conversa.' },
      ] },
    { slug:'saude-integrativa', nome:'Saúde integrativa', marca:'ecooa.health', foto:'assets/fotos/respire.webp',
      resumo:'Cuidado complementar que caminha junto do acompanhamento clínico, nunca no lugar dele.',
      escopo:['Osteopatia adulto e infantil','Nutrição funcional e integrativa','Práticas ortomoleculares','Terapia integrativa e biorressonância','Reposição de nutrientes','Cuidado complementar articulado com a equipe clínica'],
      como:['Avaliação do que já está em curso no seu cuidado.','Proposta complementar, com objetivo claro.','Comunicação com os profissionais que acompanham você.','Reavaliação conjunta.'],
      faq:[
        { q:'Terapia integrativa substitui tratamento médico?', a:'Não, e nunca é apresentada assim na ecooa. É um cuidado complementar, que existe em diálogo com o acompanhamento clínico de cada pessoa.' },
        { q:'Como sei se é indicado para mim?', a:'A avaliação inicial serve exatamente para isso. Quando não é indicado, a resposta é essa, sem rodeio.' },
      ] },
  ];

  const artigos = [
    { slug:'implante-hormonal-subcutaneo', titulo:'Implante hormonal subcutâneo: o que é e quando tem indicação', area:'medicina', esp:'medicina', tempo:'9 min de leitura', data:'2026-07-27', autor:'gustavo-gehrke',
      resumo:'Como funciona a liberação contínua, quais critérios clínicos sustentam a indicação e o que precisa ser acompanhado depois.',
      corpo:[
        ['p','O implante hormonal subcutâneo é uma via de administração, não um tratamento em si. Essa distinção parece técnica, mas muda tudo: a pergunta correta nunca é se o implante funciona, e sim se a reposição hormonal tem indicação para aquela pessoa, naquele momento, com aquele objetivo.'],
        ['h','O que a via subcutânea muda'],
        ['p','O implante libera o hormônio de forma contínua ao longo de meses, o que evita os picos e vales de outras vias. Para algumas pessoas, isso significa mais estabilidade de sintomas. Para outras, a rigidez da via é uma desvantagem, porque ajustar a dose no meio do caminho é mais difícil do que com uma apresentação diária.'],
        ['destaque','A via de administração se escolhe depois de decidir se há indicação. Nunca antes, e nunca como argumento de venda.'],
        ['h','Quem tem indicação'],
        ['p','A avaliação parte de sintomas, história clínica, exames e objetivo. Andropausa e menopausa com repercussão real na vida da pessoa, quadros de deficiência documentada, e situações em que a via contínua traz vantagem sobre as demais. Não existe indicação por idade isolada, nem por exame isolado.'],
        ['p','Há também as contraindicações, e elas são levadas a sério. Histórico oncológico hormônio dependente, eventos trombóticos, doença hepática ativa e algumas condições cardiovasculares mudam completamente a conversa.'],
        ['h','O que se acompanha depois'],
        ['p','A colocação é o começo, não o fim. Exames de controle, revisão de sintomas e reavaliação da dose fazem parte do processo. Quem propõe um implante sem combinar o acompanhamento está entregando metade do cuidado.'],
        ['p','Se você chegou até aqui procurando o procedimento, a consulta vai começar por outro lugar: entender o que está acontecendo com você. Às vezes a resposta é o implante. Às vezes é outra coisa, e dizer isso também faz parte.'],
      ] },
    { slug:'canetas-emagrecedoras-nutricao', titulo:'Canetas emagrecedoras: o que a nutrição precisa sustentar', area:'nutrição', esp:'nutricao', tempo:'8 min de leitura', data:'2026-07-27', autor:'jessica-stein',
      resumo:'Os análogos de GLP-1 mudaram o cenário do emagrecimento. O que eles resolvem, o que não resolvem, e por que a alimentação segue sendo decisiva.',
      corpo:[
        ['p','Os análogos de GLP-1 mudaram o cenário do emagrecimento nos últimos anos, e é honesto reconhecer isso. Também é honesto dizer o que eles não fazem, porque essa parte quase nunca aparece na conversa.'],
        ['h','O que a medicação faz'],
        ['p','A classe atua sobre saciedade e esvaziamento gástrico. A pessoa come menos porque sente menos fome. É um efeito real e mensurável, prescrito por médico, com indicação, dose e acompanhamento definidos na consulta.'],
        ['h','O que ela não faz'],
        ['p','Comer menos não é o mesmo que comer bem. Com apetite reduzido, o risco de ingestão proteica insuficiente é alto, e a perda de massa magra junto com a gordura é o desfecho mais comum quando ninguém acompanha a alimentação. Perder peso na balança perdendo músculo não é o objetivo de ninguém.'],
        ['destaque','A pergunta que importa não é quantos quilos saíram. É de onde eles saíram, e o que acontece quando a medicação parar.'],
        ['p','Também não se resolve sozinha a relação com a comida. Compulsão, alimentação emocional e histórico de dietas restritivas continuam ali, silenciados pelo apetite reduzido, prontos para voltar quando o efeito diminuir.'],
        ['h','O que a nutrição sustenta'],
        ['p','Ingestão proteica adequada para preservar massa magra. Densidade nutricional, porque comer pouco torna cada refeição mais decisiva. Rotina que sobreviva ao fim do tratamento. E acompanhamento da composição corporal, não só do peso.'],
        ['p','A medicação abre uma janela. O que se constrói dentro dela é o que decide se o resultado permanece.'],
      ] },
    { slug:'queda-de-cabelo-causas', titulo:'Queda de cabelo: o que investigar antes de tratar', area:'tricologia', esp:'tricologia', tempo:'8 min de leitura', data:'2026-06-18', autor:'yale-jeronimo',
      resumo:'As causas mais comuns, os exames que fazem diferença e por que o tratamento certo depende do diagnóstico.' },
    { slug:'menopausa-tratamento-hormonal', titulo:'Menopausa e terapia hormonal: o que se sabe hoje', area:'medicina', esp:'medicina', tempo:'11 min de leitura', data:'2026-06-04', autor:'gustavo-gehrke',
      resumo:'Quando a reposição faz sentido, quais os critérios de indicação e o que precisa ser acompanhado ao longo do tempo.' },
    { slug:'longevidade-saudavel', titulo:'Longevidade saudável começa nos marcadores certos', area:'longevidade', esp:'medicina', tempo:'10 min de leitura', data:'2026-05-21', autor:'gustavo-gehrke',
      resumo:'O que medir, com que frequência, e como transformar dado de exame em decisão de rotina.' },
    { slug:'equilibrio-hormonal-como-identificar', titulo:'Equilíbrio hormonal: como identificar que algo mudou', area:'medicina', esp:'medicina', tempo:'6 min de leitura', data:'2026-05-07', autor:'gustavo-gehrke',
      resumo:'Sinais que costumam ser normalizados, o que eles podem indicar e quando vale investigar.' },
    { slug:'saude-mental-emagrecimento', titulo:'Saúde mental e emagrecimento andam juntos', area:'saúde mental', esp:'saude-mental', tempo:'9 min de leitura', data:'2026-04-23', autor:'manuela-vanti',
      resumo:'Por que o acompanhamento psicológico muda o resultado de um processo de emagrecimento.' },
    { slug:'nutricao-esportiva-performance', titulo:'Nutrição esportiva: o que muda quando o treino é sério', area:'nutrição', esp:'nutricao', tempo:'6 min de leitura', data:'2026-04-09', autor:'maria-luisa-borges',
      resumo:'Periodização alimentar, recuperação e os erros mais comuns de quem treina forte.' },
    { slug:'transplante-capilar-porto-alegre', titulo:'Transplante capilar: quem tem indicação e quem não tem', area:'tricologia', esp:'transplante-capilar', tempo:'13 min de leitura', data:'2026-03-26', autor:'larissa-wiebbelling',
      resumo:'Os critérios clínicos, o que o procedimento resolve e o que ele não resolve sozinho.' },
    { slug:'rejuvenescimento-facial-porto-alegre', titulo:'Rejuvenescimento facial sem perder a expressão', area:'estética', esp:'estetica-facial', tempo:'9 min de leitura', data:'2026-03-12', autor:'eduarda-schoenmeier',
      resumo:'O que significa resultado discreto, e por que planejar o rosto inteiro importa mais do que tratar uma região.' },
    { slug:'osteopatia-o-que-e-para-quem', titulo:'Osteopatia: o que é e para quem faz sentido', area:'integrativa', esp:'saude-integrativa', tempo:'8 min de leitura', data:'2026-02-26', autor:'natalie-queiroz',
      resumo:'Como a avaliação do corpo em movimento muda a leitura de uma dor persistente.' },
    { slug:'interpretacao-exames-bioquimicos', titulo:'Seu exame não é um diagnóstico', area:'medicina', esp:'medicina', tempo:'7 min de leitura', data:'2026-02-12', autor:'jessica-stein',
      resumo:'Por que um número fora da faixa nem sempre é problema, e um dentro da faixa nem sempre é tranquilidade.' },
    { slug:'ansiedade-como-identificar-tratar', titulo:'Ansiedade: quando deixa de ser só um dia difícil', area:'saúde mental', esp:'saude-mental', tempo:'9 min de leitura', data:'2026-01-29', autor:'francielle-beria',
      resumo:'Sinais, caminhos de tratamento e o que esperar das primeiras semanas de acompanhamento.' },
    { slug:'saude-capilar-feminina', titulo:'Queda de cabelo em mulheres tem particularidades', area:'tricologia', esp:'tricologia', tempo:'10 min de leitura', data:'2026-01-15', autor:'viviane-fagundes',
      resumo:'Hormônios, ferro, ciclo e estresse. O que a investigação precisa cobrir antes de qualquer protocolo.' },
  ];

  window.ECOOA = { profissionais, grupos, especialidades, artigos };
})();
